### ISSUE TITLE
Not picking up a connection

### ISSUE THREAD

**Issue by sethcooke** [josiah-wolf-oberholtzer/discograph#62]
Hi. Discograph isn't picking up a new artist (Seth Cooke & Dominic Lash Duo) when I look up Seth Cooke. Any ideas? Great app by the way.

**Comment by josiah-wolf-oberholtzer** [comment]
Disco/graph extracts it's data from the Discogs.com *monthly* data dump (http://www.discogs.com/data/). It isn't connected directly to their database, so changes you make there will take some time to appear Disco/graph.
